In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
iris = load_iris()

In [2]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
l_score = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_score

C:\Users\arpit\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [4]:
svm_score = cross_val_score(SVC(), iris.data, iris.target)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [5]:
rfc_score = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rfc_score

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [6]:
np.mean(l_score)

np.float64(0.9733333333333334)

In [7]:
np.mean(svm_score)

np.float64(0.9666666666666666)

In [8]:
np.mean(rfc_score)

np.float64(0.9666666666666668)

**The accuracy of the Logistic Regression model is more than the SVM and the Random Forest Classifier**